fix for 1904633
CanonicalLtd/netplan pull request #172
Opened 2020-11-18 19:22 UTC by iaroslavscript

## Description
Hi! This is a fix for [1904633](https://bugs.launchpad.net/netplan/+bug/1904633) **netplan** crashes while loading incorrect config. 

## Testcase

Bellow is a minimal reproducible config. It wasn't my aim to create a malfunction config I just thought that it's possible to define a `renderer` for a subgroup of interfaces.

```
root@pc:/# cat /etc/netplan/01-network-manager-all.yaml
network:
  version: 2
  wifis:
    renderer: NetworkManager
```
```
root@pc:/# netplan try

An error occurred: 'str' object has no attribute 'get'

Reverting.
Traceback (most recent call last):
  File "/usr/share/netplan/netplan/cli/commands/try_command.py", line 83, in command_try
    NetplanApply().command_apply(run_generate=True, sync=True, exit_on_error=False)
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 154, in command_apply
    NetplanApply.process_ovs_cleanup(config_manager, old_files_ovs, restart_ovs, exit_on_error)
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 324, in process_ovs_cleanup
    apply_ovs_cleanup(config_manager, ovs_old, ovs_current)
  File "/usr/share/netplan/netplan/cli/ovs.py", line 119, in apply_ovs_cleanup
    if (is_ovs_interface(i, config_manager.interfaces)):
  File "/usr/share/netplan/netplan/cli/ovs.py", line 102, in is_ovs_interface
    if interfaces[iface].get('openvswitch') is not None:
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/netplan", line 23, in <module>
    netplan.main()
  File "/usr/share/netplan/netplan/cli/core.py", line 50, in main
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 211, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/try_command.py", line 66, in run
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 211, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/try_command.py", line 94, in command_try
    self.revert()
  File "/usr/share/netplan/netplan/cli/commands/try_command.py", line 117, in revert
    NetplanApply().command_apply(run_generate=False, sync=True, exit_on_error=False)
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 154, in command_apply
    NetplanApply.process_ovs_cleanup(config_manager, old_files_ovs, restart_ovs, exit_on_error)
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 324, in process_ovs_cleanup
    apply_ovs_cleanup(config_manager, ovs_old, ovs_current)
  File "/usr/share/netplan/netplan/cli/ovs.py", line 119, in apply_ovs_cleanup
    if (is_ovs_interface(i, config_manager.interfaces)):
  File "/usr/share/netplan/netplan/cli/ovs.py", line 102, in is_ovs_interface
    if interfaces[iface].get('openvswitch') is not None:
AttributeError: 'str' object has no attribute 'get'
root@pc:/#

```

The exception happens because *interface* supposed to be a `dict` not any other type.

I've found a comment that it's planning to get rid of parsing configs in python [configmanager.py#L93](https://github.com/CanonicalLtd/netplan/blob/0.100/netplan/configmanager.py#L93) So in this pull request a made only a quick fix.

2020-11-20 13:50 UTC, slyon commented
Hey Iaroslav, thank you very much for reporting this bug and starting to work on it right away!
I can reproduce the problem on my machine.

Your proposed change looks pretty big, though. I think a simple change in `netplan/cli/ovs.py` should be enough to fix the root cause of this problem (in line 102). Something like this:
```
diff --git a/netplan/cli/ovs.py b/netplan/cli/ovs.py
index a7ae6c8..ab3cb4c 100644
--- a/netplan/cli/ovs.py
+++ b/netplan/cli/ovs.py
@@ -99,7 +99,9 @@ def clear_setting(type, iface, setting, value):
 
 
 def is_ovs_interface(iface, interfaces):
-    if interfaces[iface].get('openvswitch') is not None:
+    if not isinstance(interfaces[iface], dict):
+        return False
+    elif interfaces[iface].get('openvswitch') is not None:
         return True
     else:
         return any(is_ovs_interface(i, interfaces) for i in interfaces[iface].get('interfaces', []))
```

Also, adding a small test case in `tests/generator/test_ovs.py` (using your minimal reproducer) to make tests & coverage happy would be great.
Would you be willing to re-work this PR accordingly?

2020-11-20 13:51 UTC, slyon requested changes
Hey Iaroslav, thank you very much for reporting this bug and starting to work on it right away!
I can reproduce the problem on my machine.

Your proposed change looks pretty big, though. I think a simple change in `netplan/cli/ovs.py` should be enough to fix the root cause of this problem (in line 102). Something like this:
```
diff --git a/netplan/cli/ovs.py b/netplan/cli/ovs.py
index a7ae6c8..ab3cb4c 100644
--- a/netplan/cli/ovs.py
+++ b/netplan/cli/ovs.py
@@ -99,7 +99,9 @@ def clear_setting(type, iface, setting, value):
 
 
 def is_ovs_interface(iface, interfaces):
-    if interfaces[iface].get('openvswitch') is not None:
+    if not isinstance(interfaces[iface], dict):
+        return False
+    elif interfaces[iface].get('openvswitch') is not None:
         return True
     else:
         return any(is_ovs_interface(i, interfaces) for i in interfaces[iface].get('interfaces', []))
```

Also, adding a small test case in `tests/generator/test_ovs.py` (using your minimal reproducer) to make tests & coverage happy would be great.
Would you be willing to re-work this PR accordingly?

2020-11-21 08:04 UTC, iaroslavscript commented
Hi @slyon,
Thanks for the review.
Sure. I will rework!

2020-11-27 12:48 UTC, slyon approved these changes
Hey @iaroslavscript sorry for cutting the line here and pushing my own changes.
There is another bug related to a very similar issue ([LP: #1905156](https://pad.lv/1905156)) and we're working on a new release where we want to have those fixes included.

Thank you very much for your contribution, test case and minimal reproducer. This is much appreciated! Also, let me know what you think about my proposed changes in this PR.

Maybe @sil2100 could have another look as well?

2020-11-27 14:34 UTC, sil2100 approved these changes
Looks correct. Indeed this was something we missed considering during the OVS code addition. Thank you Iaroslav, Lukas!

2020-11-27 14:34 UTC, merged

2020-12-01 08:47 UTC, iaroslavscript commented
Hi @slyon 

I'm very glad this case is closed and the problem is solved. Thanks for taking care about it, I was a little bit busy on my regular job that week.

LGFM! The only thing I worry about is that the warning of skipped key is displayed only in debug logging mode. You can miss it when applying configuration until you actually verify the result. I would propose to display it always.

2020-12-01 08:49 UTC, iaroslavscript commented
@slyon @sil2100 :+1:

2020-12-08 10:27 UTC, marcoBros commented
How can we apply this patch whitout waiting for package distribution via apt ?

2020-12-09 11:28 UTC, slyon commented
> @iaroslavscript
> How can we apply this patch whitout waiting for package distribution via apt ?

@marcoBros you could modify the file on disk accordingly (`/usr/share/netplan/netplan/cli/ovs.py`) but this is not recommended – do it at your own risk.