doc: Add documentation for get/set CLI and Config/Try/Cancel/Apply/Get/Set DBus methods
CanonicalLtd/netplan pull request #173
Opened 2020-11-23 14:36 UTC by slyon

## Description
Add man pages for `netplan get/set` CLI and `Config/Try/Cancel/Apply/Get/Set` DBus methods

## Checklist

- [x] Runs `make check` successfully.
- [x] Retains 100% code coverage (`make check-coverage`).
- [x] New/changed keys in YAML format are documented.
- [x] \(Optional\) Adds example YAML for new feature.
- [ ] \(Optional\) Closes an open bug in Launchpad.

2020-11-23 17:00 UTC, sil2100 requested changes
The resulting manpages look good, but I'd like it if you could include information about the config invalidation - as per my inline comment.

Post 0.101 I think it would be also nice if we included some examples for people (probably somehow in `examples`? Though right now we only have `.yaml` configs there...), showing a typical DBus interaction scenario. Since then it would be easier for them to understand how the interactions with a config object are supposed to be performed to get a modified config applied from start to the end.

2020-11-24 08:44 UTC, slyon commented on doc/netplan-dbus.md
> + * ``Set(s:CONFIG_DELTA, s:ORIGIN_HINT) -> b``: calls **netplan set --root-dir=/tmp/netplan-config-ID --origin-hint=<ORIGIN_HINT> CONFIG_DELTA**, where CONFIG_DELTA can be something like: ``network.e
I've extended the description of `Set()` a bit, to explain the conflict  management.

2020-11-24 08:47 UTC, slyon commented
Thank you! I've updated the `netplan-dbus.8` manpage accordingly and also added a brief DBus config management scenario in `examples/dbus_config_scenario.txt`, by showing the control flow via `busctl` commands.

2020-11-24 19:03 UTC, sil2100 approved these changes
Sweet! Thank you!

2020-11-24 19:03 UTC, merged